#!/usr/bin/env bash
#
# Build the Porchlight Lambda bundle — no Docker, no emulation.
#
# `uv` can resolve and download wheels for a platform it is not running on, so a macOS arm64
# laptop can produce a Linux arm64 (Graviton) bundle as long as every dependency ships a
# manylinux aarch64 wheel (`--only-binary=:all:` makes a source-only dependency a loud failure
# instead of a broken deploy).
#
# Output:
#   build/requirements-lambda.txt   what went in (generated from pyproject.toml)
#   build/lambda/                   the deployable directory — CDK's `Code.fromAsset` target
#   build/porchlight-lambda.zip     the same tree zipped, for inspecting size and contents
#
# The bundle's entry points:
#   run.sh                  started by the Lambda Web Adapter layer (the API)
#   api.scheduled.handler   the hourly sweep / nightly brief
#   api.lambda_handler.handler  Mangum, the buffered alternative to the adapter
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${ROOT}/build"
BUNDLE_DIR="${BUILD_DIR}/lambda"
REQUIREMENTS="${BUILD_DIR}/requirements-lambda.txt"
ZIP_PATH="${BUILD_DIR}/porchlight-lambda.zip"

PY_VERSION="${LAMBDA_PYTHON_VERSION:-3.12}"
PLATFORM="${LAMBDA_PLATFORM:-aarch64-manylinux2014}"
APP_PORT="${LAMBDA_APP_PORT:-8000}"

# Installed without their dependency trees: only `current_time` is used from strands-agents-tools,
# and its full tree (pillow, sympy, aiohttp, slack-bolt, ...) would add ~70 MB of dead weight.
NO_DEPS_PACKAGES=("strands-agents-tools")

# Lambda's hard limit on the unzipped function package, in megabytes.
UNZIPPED_LIMIT_MB=250

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
fail() { printf '\033[31merror: %s\033[0m\n' "$1" >&2; exit 1; }

command -v uv >/dev/null 2>&1 || fail "uv is required (https://docs.astral.sh/uv/); brew install uv"

PYTHON_BIN="${ROOT}/.venv/bin/python"
[ -x "${PYTHON_BIN}" ] || PYTHON_BIN="$(command -v python3 || true)"
[ -n "${PYTHON_BIN}" ] || fail "no python3 found to read pyproject.toml"

step "Clearing ${BUNDLE_DIR}"
rm -rf "${BUNDLE_DIR}" "${ZIP_PATH}"
mkdir -p "${BUNDLE_DIR}"

step "Generating ${REQUIREMENTS} from pyproject.toml"
NO_DEPS_CSV="$(IFS=,; echo "${NO_DEPS_PACKAGES[*]}")" \
"${PYTHON_BIN}" - "${ROOT}/pyproject.toml" "${REQUIREMENTS}" <<'PY'
"""Turn [project].dependencies into a requirements file, minus the no-deps packages."""
import os
import re
import sys
import tomllib
from pathlib import Path

pyproject, output = Path(sys.argv[1]), Path(sys.argv[2])
data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
deps = list(data["project"]["dependencies"])
skip = {name.strip().lower() for name in os.environ.get("NO_DEPS_CSV", "").split(",") if name.strip()}


def canonical(spec: str) -> str:
    """The distribution name of a requirement string, normalised the way PyPI does."""
    name = re.split(r"[<>=!~\[; ]", spec.strip(), maxsplit=1)[0]
    return re.sub(r"[-_.]+", "-", name).lower()


kept = [dep for dep in deps if canonical(dep) not in skip]
dropped = [dep for dep in deps if canonical(dep) in skip]

lines = [
    "# Generated by scripts/build_lambda.sh from pyproject.toml [project].dependencies.",
    "# Dev dependencies are never bundled.",
]
if dropped:
    lines.append("# Installed separately with --no-deps: " + ", ".join(sorted(dropped)))
lines += sorted(kept)
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"{len(kept)} runtime dependencies -> {output}")
PY

step "Installing wheels for ${PLATFORM} / python ${PY_VERSION}"
uv pip install \
  --python-platform "${PLATFORM}" \
  --python-version "${PY_VERSION}" \
  --only-binary=:all: \
  --target "${BUNDLE_DIR}" \
  --quiet \
  --requirement "${REQUIREMENTS}"

for package in "${NO_DEPS_PACKAGES[@]}"; do
  step "Installing ${package} (--no-deps)"
  uv pip install \
    --python-platform "${PLATFORM}" \
    --python-version "${PY_VERSION}" \
    --only-binary=:all: \
    --target "${BUNDLE_DIR}" \
    --no-deps \
    --quiet \
    "${package}"
done

step "Copying the porchlight and api packages"
for package in porchlight api; do
  [ -d "${ROOT}/${package}" ] || fail "missing source package ${ROOT}/${package}"
  rm -rf "${BUNDLE_DIR:?}/${package}"
  cp -R "${ROOT}/${package}" "${BUNDLE_DIR}/${package}"
done

step "Writing the Lambda Web Adapter bootstrap (run.sh)"
cat > "${BUNDLE_DIR}/run.sh" <<EOF
#!/bin/sh
# Started by the Lambda Web Adapter layer (AWS_LAMBDA_EXEC_WRAPPER=/opt/bootstrap).
# The adapter proxies the Lambda invocation to uvicorn on \${AWS_LWA_PORT}.
set -e
export PYTHONPATH="\${LAMBDA_TASK_ROOT:-/var/task}:\${PYTHONPATH:-}"
PY=python3
command -v "\$PY" >/dev/null 2>&1 || PY=python
exec "\$PY" -m uvicorn api.main:app --host 0.0.0.0 --port "\${PORT:-${APP_PORT}}"
EOF
chmod 755 "${BUNDLE_DIR}/run.sh"

step "Pruning build noise"
find "${BUNDLE_DIR}" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "${BUNDLE_DIR}" \( -name '*.pyc' -o -name '*.pyo' -o -name '.DS_Store' \) -delete 2>/dev/null || true
rm -rf "${BUNDLE_DIR}/bin"

# --- checks -------------------------------------------------------------------------------
step "Checking the bundle"
for required in run.sh api/main.py api/scheduled.py api/lambda_handler.py porchlight/graph.py \
                uvicorn/__init__.py fastapi/__init__.py strands/__init__.py boto3/__init__.py \
                strands_tools/current_time.py; do
  [ -e "${BUNDLE_DIR}/${required}" ] || fail "bundle is missing ${required}"
done
[ -x "${BUNDLE_DIR}/run.sh" ] || fail "run.sh is not executable"

# Every compiled extension must be Linux aarch64, not the host's macOS/x86 build.
WRONG_ARCH="$(find "${BUNDLE_DIR}" -name '*.so' ! -name '*cpython-312-aarch64-linux-gnu.so' \
  ! -name '*.abi3.so' -print | head -5 || true)"
if [ -n "${WRONG_ARCH}" ]; then
  printf '\033[33mwarning: unexpected shared objects (check the target platform):\033[0m\n%s\n' "${WRONG_ARCH}"
fi

step "Zipping ${ZIP_PATH}"
(cd "${BUNDLE_DIR}" && zip -qr "${ZIP_PATH}" . -x '*.DS_Store')

# --- report -------------------------------------------------------------------------------
UNZIPPED_KB="$(du -sk "${BUNDLE_DIR}" | awk '{print $1}')"
UNZIPPED_MB=$(( UNZIPPED_KB / 1024 ))
ZIP_MB="$(du -m "${ZIP_PATH}" | awk '{print $1}')"
FILE_COUNT="$(find "${BUNDLE_DIR}" -type f | wc -l | tr -d ' ')"

printf '\n\033[1m==> Bundle\033[0m\n'
printf '  directory : %s\n' "${BUNDLE_DIR}"
printf '  zip       : %s\n' "${ZIP_PATH}"
printf '  unzipped  : %s MB (Lambda limit %s MB)\n' "${UNZIPPED_MB}" "${UNZIPPED_LIMIT_MB}"
printf '  zipped    : %s MB\n' "${ZIP_MB}"
printf '  files     : %s\n' "${FILE_COUNT}"
printf '  platform  : %s, python %s, arm64\n' "${PLATFORM}" "${PY_VERSION}"
printf '\n  largest packages:\n'
du -sk "${BUNDLE_DIR}"/* 2>/dev/null | sort -rn | head -12 |
  awk '{ printf "    %6.1f MB  %s\n", $1/1024, $2 }'

if [ "${UNZIPPED_MB}" -ge "${UNZIPPED_LIMIT_MB}" ]; then
  fail "bundle is ${UNZIPPED_MB} MB unzipped; Lambda's limit is ${UNZIPPED_LIMIT_MB} MB"
fi

printf '\n\033[32mok\033[0m — deploy it with: make deploy-infra\n'
